# Reading CSV Tax Data Files
We will be testing to ensure we can import and view the tax data csv files.

In [1]:
import pandas as pd

In [2]:
df2020 = pd.read_csv("../data/tax_data_2020.csv")
df2019 = pd.read_csv("../data/tax_data_2019.csv")

In [3]:
df2020.head(10)

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,ELF,CPREP,...,N85300,A85300,N11901,A11901,N11900,A11900,N11902,A11902,N12000,A12000
0,1,AL,0,1,785000.0,519980.0,85690.0,165290.0,724170.0,22560.0,...,0.0,0.0,57720.0,46577.0,674840.0,1827202.0,672200.0,1818867.0,2900.0,6089.0
1,1,AL,0,2,554310.0,270870.0,121420.0,146470.0,515150.0,13260.0,...,0.0,0.0,81770.0,112540.0,470410.0,1445383.0,466960.0,1432458.0,4660.0,11648.0
2,1,AL,0,3,290630.0,113280.0,124770.0,44570.0,269700.0,6420.0,...,0.0,0.0,70360.0,144380.0,220710.0,626662.0,216530.0,610170.0,5760.0,16235.0
3,1,AL,0,4,181010.0,42010.0,120820.0,14410.0,168830.0,2570.0,...,0.0,0.0,49500.0,135429.0,130670.0,437179.0,126790.0,419324.0,3730.0,14903.0
4,1,AL,0,5,269080.0,31310.0,224330.0,8270.0,252360.0,3250.0,...,100.0,20.0,103250.0,470206.0,165650.0,724529.0,156910.0,642895.0,11280.0,80064.0
5,1,AL,0,6,81340.0,5000.0,72270.0,630.0,76810.0,230.0,...,41750.0,164094.0,43960.0,1216690.0,34560.0,735671.0,24770.0,285560.0,9630.0,391783.0
6,1,AL,35004,1,1460.0,1010.0,200.0,210.0,1340.0,40.0,...,0.0,0.0,110.0,80.0,1210.0,2807.0,1210.0,2795.0,0.0,0.0
7,1,AL,35004,2,1400.0,760.0,280.0,310.0,1310.0,40.0,...,0.0,0.0,190.0,194.0,1210.0,3378.0,1200.0,3335.0,30.0,62.0
8,1,AL,35004,3,1020.0,460.0,350.0,190.0,970.0,30.0,...,0.0,0.0,230.0,357.0,800.0,2131.0,790.0,2119.0,0.0,0.0
9,1,AL,35004,4,630.0,140.0,420.0,60.0,590.0,0.0,...,0.0,0.0,180.0,386.0,450.0,1282.0,440.0,1276.0,0.0,0.0

In [4]:
df2019.head(10)

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,ELF,CPREP,...,N85300,A85300,N11901,A11901,N11900,A11900,N11902,A11902,N12000,A12000
0,1,AL,0,1,778210.0,491030.0,84770.0,189600.0,712890.0,30670.0,...,0.0,0.0,62720.0,51936.0,671860.0,1700965.0,669570.0,1694792.0,1980.0,3512.0
1,1,AL,0,2,525940.0,247140.0,123910.0,139860.0,481760.0,18960.0,...,0.0,0.0,85860.0,122569.0,438020.0,1274802.0,435210.0,1266557.0,3670.0,7410.0
2,1,AL,0,3,285700.0,105140.0,128140.0,44560.0,260570.0,10670.0,...,0.0,0.0,73980.0,154932.0,212040.0,575315.0,208470.0,564202.0,5020.0,13653.0
3,1,AL,0,4,179070.0,38820.0,123110.0,13740.0,164300.0,5020.0,...,0.0,0.0,51330.0,139065.0,126850.0,401581.0,123310.0,388749.0,3040.0,10377.0
4,1,AL,0,5,257010.0,28180.0,216740.0,7150.0,236850.0,8400.0,...,90.0,141.0,104290.0,460071.0,152790.0,598248.0,144640.0,539385.0,9180.0,56257.0
5,1,AL,0,6,74810.0,4540.0,66580.0,530.0,69330.0,1760.0,...,39430.0,141243.0,40030.0,946610.0,32060.0,681565.0,22420.0,257633.0,9450.0,372747.0
6,1,AL,35004,1,1450.0,990.0,180.0,250.0,1320.0,60.0,...,0.0,0.0,120.0,100.0,1230.0,2383.0,1220.0,2365.0,0.0,0.0
7,1,AL,35004,2,1370.0,700.0,280.0,340.0,1260.0,50.0,...,0.0,0.0,220.0,261.0,1150.0,2995.0,1140.0,2984.0,0.0,0.0
8,1,AL,35004,3,970.0,410.0,370.0,160.0,900.0,50.0,...,0.0,0.0,240.0,410.0,730.0,1814.0,720.0,1799.0,40.0,46.0
9,1,AL,35004,4,650.0,130.0,460.0,60.0,610.0,0.0,...,0.0,0.0,170.0,391.0,480.0,1666.0,470.0,1468.0,0.0,0.0

In [5]:
df2020.shape

(166452, 165)

In [6]:
df2019.shape

(166159, 152)

In [7]:
df2020.dtypes

STATEFIPS      int64
STATE         object
zipcode        int64
agi_stub       int64
N1           float64
              ...
A11900       float64
N11902       float64
A11902       float64
N12000       float64
A12000       float64
Length: 165, dtype: object

In [8]:
df2019.dtypes

STATEFIPS      int64
STATE         object
zipcode        int64
agi_stub       int64
N1           float64
              ...
A11900       float64
N11902       float64
A11902       float64
N12000       float64
A12000       float64
Length: 152, dtype: object

In [9]:
df2020["STATE"].value_counts().head(10)

TX    9702
NY    9234
CA    8898
PA    8219
IL    7379
OH    5988
FL    5526
MI    5352
MO    5351
IA    4950
Name: STATE, dtype: int64